### ISSUE TITLE
[client] Dodanie obsługi kilku markerów

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/PlaceTag#1]

**Comment by debian-sh** [comment]
Super, jedynie co musimy tutaj poprawić to, że nowo wpisany marker w tablicy locations `		locations.push(marker);` nie jest tablicą z 4 danymi a całym obiektem z dużą ilością zbędnych danych.

![selection_007](https://cloud.githubusercontent.com/assets/5663277/6545993/435d0b34-c5a1-11e4-8775-5b761bb834f2.png)

Nasz dodany obiekt pod indeksem position zawiera informację, które musimy wyciągnąć.

<code>
position:
D: 16.92967414855957
k: 52.46620723386413
</code>

i dopiero pushnąć do tablicy locations, musimy też stwierdzić co byłoby lepsze tablica obiektów czy tablica tablic :) Tak żeby później wiedzieć jak parsować dane bo będziemy je ściągać z RESTowego API w JSONie z MongoDB (przez Sealiousa)

**Comment by debian-sh** [comment]
Po dokładniejszym przetestowaniu kodu, należy pozostać chyba przy obiektach markerów, ponieważ podczas przesuwania już utworzonych markerów aktualizowana jest ich pozycja.


Jeśli dodamy 
 ```javascript
 locations.push(['tag', marker.position.k, marker.position.D, locations.length+1]);
 ```
Nasz nowo dodany marker jest wpisany do tablicy, ale nie możliwości jego zaktualizowania.
Jeśli wpisujemy to za pomocą
 ```javascript
 locations.push(marker);
 ```
To możemy przesuwać je po mapie i się elegancko aktualizują.

Do kodu dostarczamy tablicę locations, z lokalizacją danego miejsca no i problem jest tego typu, że zmieniając jedo pozycję na mapie nie aktualizujemy jego pozycji.

Mój pomysł jest następujący:

**Comment by modliszka** [comment]
I elegancko. :D

**Comment by debian-sh** [comment]
zamykamy te issue, ciąg dalszy w issue#9
