### ISSUE TITLE
Add spinner for loading tiles

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#103]
https://github.com/ebrelsford/Leaflet.loading

**Comment by debian-sh** [comment]
![image](https://cloud.githubusercontent.com/assets/5663277/9561209/6dc4fed0-4e3c-11e5-8c45-1eb54acd3595.png)

![image](http://placetag.pl/img/spinner.gif)
Aktualnie jest coś takiego, wymaga poprawki (brak wygładzenia).

**Comment by debian-sh** [comment]
Zajmiesz się tym?

**Comment by Porkite** [comment]
spojrzę na to w weekend

**Comment by debian-sh** [comment]
ok! :)

**Comment by debian-sh** [comment]
zawieszam.
