### ISSUE TITLE
Refractoring PlacesCategory

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#106]

**Comment by debian-sh** [comment]
@Porkite @madjer22 @modliszka proponuje kilka nowych rozwiązań

1. Wyświetlać tylko odpowiednie kategorie w formie listy jak miejsca i tylko te, które mają odwzierciedlenie w miejscach? Czyli nie pokazywać kategorii, które nie zostały w wybrane przy dodawaniu miejsc.

2. Przy wspomnianej liście w punkcie 1 można np. na końcu nazwy kategorii dodać cyfrę określającą liczbę miejsc zdefiniowanej w tej kategorii.

3. Rezygnacja z podkategorii. Nastawić się na prostotę i pozostać przy kategoriach, które już ładnie porządkują dużą ilość miejsc.

4. Może wprowadzić zamiast podkategorii #tagi ale co one mogłyby dawać w kwestii użyteczności to nie mam pojęcia.

**Comment by debian-sh** [comment]
https://www.youtube.com/watch?v=pYS2N8GbkqQ

**Comment by madjer22** [comment]
1. hmm, kwestia tego jak sie komu bardziej podoba, forma listy sprawia ze rzeczywiscie mozna wyswietlac tylko te ktore juz cos maja
2. jak najbardziej
3. mysle ze poki co zostanmy przy podkategoriach takze, zrobmy zmiany i wtedy wrocimy do tematu czy rzeczywiscie jest sens
4. nie lubie tagow, praktycznie nie uzywam, uzylem raz w zyciu, jestem na nie

**Comment by debian-sh** [comment]
do 3. Wydaje mi się wysoce nadmiarowe używanie podkategorii. Tymbardziej jeśli istnieje przypadek w, którym user bez problemu przyporządkuje swoje miejsce do Kateogrii zaś żadna z Podkategorii już nie pasuje?

**Comment by Porkite** [comment]
1. Wyświetlamy wszystkie.
2. Bardzo spoko. Jako że wszystkie kategorie będą wyświetlone, będzie widać gdzie mamy tagi, a gdzie nie.
3. Jestem za rezygnacją
4. Nie mam zdania.

Proponuję się jakoś spotkać w tygodniu.

**Comment by debian-sh** [comment]
zawieszam.
