### ISSUE TITLE
Próba podsumowania nowych zadań w projekcie

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#109]
...

**Comment by debian-sh** [comment]
Backend:

* Wprowadzenie obsługi wielu kont użytkowników, którzy mają własne zasoby
* Rozszerzenie zasobu user

===
Frontend:

* Przepisanie komponentu kategorii
* Rezygnacja z podkategorii
* Wprowadzenia hasztagów / opisu z hasztagami
* Przetestowanie nowego, dodatkowego geocodera
* Poprawa zwracanych wyników przez aktualny geocoder
* Wprowadzenie ustawień dla usera
* Próba zmiany Leaflet na nową wersję
* Shareowanie na twittera i inne wybrane serwisy
* Dodawanie nowego miejsca przez wybranie miejsca sharowanego z facebooka/twittera
* Pełnoekranowy podgląd zdjęcia


===
UI:

* Strona główna z paralax
* Nowy wygląd markerów
* Zmiana wyświetlania listy
* Prosty mobile view dla webowej wersji Placetaga
* Poprawa spinnera dla ładowania kafelków mapy

==
Android:

* Nowa wersja aplikacji (material design)

**Comment by modliszka** [comment]
Co rozumiesz przez "Rozszerzenie zasobu user". Czy chodzi Ci o coś w stylu "Moje konto"+"Ustawienia konta"?

**Comment by debian-sh** [comment]
User przy zakładaniu konta będzie mógł wypełnić więcej pól. W ustawieniach konta będzie można wybrać miasto docelowe etc.

**Comment by debian-sh** [comment]
@madjer22 @Porkite proszę ogarnijcie temat

**Comment by debian-sh** [comment]
W kwestii opisu i hasztagów wypracowałem rozwiązanie. Możemy zrobić własne pole typu opis, jako argument zostanie wysłany ciąg znaków. Zaś serwer odczyta treść i pod polem opis w konkretnym zasobie zostanie umieszczony obiekt o dwóch właściwościach: jeden to będzie opis, a drugi - tablica wyfiltrowanych hasztagów z opisu.

**Comment by modliszka** [comment]
Ale to chyba trzeba będzie mieć jakąś "podstawową" bazę hashtagów, prawda?

**Comment by debian-sh** [comment]
Nie nie będzie żadnej bazy hashtagów, generowane będą na podstawie opisu.

Po wypełnieniu pola opisu np. "Dobra chińska restauracja #kurczak #tanio"

Pole typu opis w zasobie danego miejsca będzie wyglądać następująco:
```js
description:{
    summary: "Dobra chińska restauracja #kurczak #tanio",
    tags: ['#kurczak', '#tanio']
}
```

**Comment by Porkite** [comment]
Spoko pomysł z hasztagami, tylko użytkownik musi wiedzieć o tym, że może nimi walić, ale to już kwestia UX. Ogólnie idziemy w stabilizację i głaskanie. Na wtorek przygotuję prezentację w której spróbuję uogólnić jaki mamy cel na ten semestr.

**Comment by madjer22** [comment]
Przekonuje sie w kwesti eliminacji podkategorii i pojscia w hasztagi. Mysle ze zdecydowanie powinnismy sobie postawic za cel glowny, to aby byly te dzielone zasoby, na obsluge uzytkownikow. Czyli prywatny organizer dla kazdego. Jak to bedziemy mieli juz sprawnie dzialajace to dla mnie takie clue, nie spolecznosciowka, ale jakas namiastka tego poprzez mozliwosc dodania znajomej osoby czy tez podgladania profilu jakiegos miasta. Dzieki temu bedziemy mogli dodac do swojej kolekcji czyjes miejsca. Jesli to bysmy zrobili, to moze warto sprobowac pojsc w kolekcje miejsc, czyli podroz, trase - zbior miejsc. I tak np. osoba, ktora jedzie na wycieczke weekendowa, miejsca, ktore sobie juz szykuje w domu, moze zgromadzic w jedna wycieczke. I tak, powiedzmy Arek, ktory byl we Wladyslawowie i ktoremu bardzo sie podobalo, rekomenduje mi to miejsce w jakiejs rozmowie prywatnej. Ja zachecona opowiesciami Arka, importuje sobie jego cala trase na swoj profil i ciesze sie zwiedzaniem.

**Comment by debian-sh** [comment]
Ok ale to plan na znacznie więcej niż 4 miesiące zatem może idźmy na razie w kierunku "mój własny organizer" a dzielenie się miejscami przez ogólnodostępne sieci społecznościowe jest ok. Po wybraniu takiego miejsca jesteśmy przekierowani na  wyspecyfikowany adres, gdzie albo będziemy mogli tylko zobaczyć miejsce lub też je dodać do swoich.

**Comment by madjer22** [comment]
Docelowo nie wyobrazam sobie dodawac miejsce tylko przez sieci spolecznosciowe, sa ludzie ktorzy nie lubia i nie maja spolecznosciowek. Docelowo chcialbym wejsc na Twoj profil i dodac miejsce jakies Twoje do siebie, a nie korzystac, gdy czesto nie mam ze spolecznosciowki. Wiadomo, ze przy profilu bedzie trzeba przyjac jakas strategie

**Comment by debian-sh** [comment]
Ja nie korzystam ze społecznościówek. I w ogóle moim zdaniem nie ma sensu tworzenie sieci społecznościowej, bo jest tego sporo. W aktualnym poziomie zaawansowania frameworka chyba jesteśmy w stanie implementować tego typu rozwiązania.

**Comment by Porkite** [comment]
Ok, czyli jutro na prezentacji poruszamy następujące kwestie:
1. Idziemy w kierunku naszego prywatnego organizera. Nie wchodzimy w system znajomych ani profili publicznych, ponieważ w tak krótkim czasie nie jesteśmy w stanie dopiąć tego, aby działało dobrze.
2. Zbudowanie od nowa aplikacji mobilnej, która jest bardziej responsywna i wizualnie ładniejsza.
3. Umożliwienie tworzenia nowych kont z osobnymi zasobami.
4. Modyfikacja wyglądu strony webowej w oparciu o ux, czyli zmiany w:
- kategoriach/podkategoriach,
- liście/sortowaniu, 
- dodanie ustawień użytkownika,
- ekran logowania/strona główna,
- elementy graficzne interfejsu oraz logo.
5. Dodanie funkcjonalności hashtagów oraz wyszukiwania po nich.
6. Rozszerzenie funkcjonalności dzielenia się miejscami.
Proszę o weryfikację, czy o czymś nie zapomniałem, co jest warte wspomnienia.

**Comment by modliszka** [comment]
Wiadomo jak się dzielimy zadaniami? Myślę, że warto wiedzieć mniej więcej co i kto przed prezentacją ;)

**Comment by debian-sh** [comment]
@Porkite wszystko ok, @modliszka jutro omówimy ten temat, będę potrzebował dużego wsparcia zwłaszcza jeśli chodzi o Reacta i większego zaangażowania w projekt mamy mniej czasu na dopięcie.

**Comment by Porkite** [comment]
Tu jest prezentacja http://slides.com/porkite/placetag-1
Zajmie mi ona około 5 min.
Jeżeli macie pomysł o co ją rozbudować, to proszę piszcie.

**Comment by debian-sh** [comment]
1. Błąd: "- Rozbudowanie funcjonalności dzielenia się miejscami" 
2. Listę lepiej wyrównać do lewej
3. Może ostatni slajd podzielić na podtematy (backend, frontend, mobilna aplikacja, UX, ujednolicenie interfejsów pomiędzy apką mobilną a boxem frontendu)

**Comment by Porkite** [comment]
Co masz na myśli przez rozbicie na podtematy?
Podczas prezentacji wspominam o UX, o mobilce i w potrzebnych w niej zmianach względem frontendu webowej.
