### ISSUE TITLE
Sprawdzenie API Leaflet

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#11]
Obadać przykłady implementacji, porównać czy jest to prostsze niż w Google API v3.

**Comment by modliszka** [comment]
Poniżej zamieszczam linki przydatne do rozpoznania leaflet'a
http://gis.stackexchange.com/questions/21890/does-leaflet-js-api-provide-a-geocoding-service
https://github.com/sa3m/leaflet-control-bing-geocoder
http://developer.mapquest.com/pl/web/documentation/plugins/leaflet/v1.0/geocoding
http://leafletjs.com/reference.html

**Comment by debian-sh** [comment]
Myślę, że ten issue można zamknąć. Dalsze prace w https://github.com/debian-sh/Placetag/issues/15
