### ISSUE TITLE
Przemyśleć sposób wyświetlania zbyt długich nazw miejsc

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#111]
![image](https://cloud.githubusercontent.com/assets/9070671/10513488/32cfe52a-7348-11e5-94e8-43643bffc328.png)
Jak na obrazku - wynik zwrócił kilka różnych miejsc, a dlatego, że jest za duża czcionka, pojawiają się dwa wiersze i reszty nie widać. Efekt? wygląda jakby były powtórzenia.

Trzeba przemyśleć, jak takie sytuacje rozwiązać. 

Pobrany json:
http://nominatim.openstreetmap.org/?format=json&addressdetails=1&accept-language=pl-PL&q=Cyklo%C5%9Bcie%C5%BCka%20Szlakiem%20Kolei%20W%C4%85skotorowej

**Comment by debian-sh** [comment]
Myślę, że lista powinna być "bardziej drobna"
