### ISSUE TITLE
Wersja aplikacji bez logowania z wykorzystaniem cookies i localStorage + wersja z logowaniem

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#122]
Nie wiem jak bardzo task: **dwa stany aplikacji (cookie + server) - podział zachowania aplikacji** jest powiązany z taskiem: **wprowadzenie mechanizmu cookies do zapisywania miejsc bez rejestracji**, dlatego zaznaczyłam póki co ten drugi dla siebie.

Myślę, że można by było użyć pluginu:
https://github.com/eXon/react-cookie

I zastanawiam się jak trzeba będzie użyć tego w całej apce. Skoro dane mają być w cookies, to nie będą wysyłane na serwer -> czy to oznacza że trzeba będzie zrobić cały odrębny kod na zarządzanie stronką, czy jednak będzie można współdzielić kod i tylko robić odpowiednie przekierowania do sposobu tworzenia zasobów? @debian-sh mogę prosić o komentarz?

**Comment by debian-sh** [comment]
Ten plugin jest spoko, używałem już go tutaj https://github.com/Sealious/sealious-channel-rest/tree/issue%231_rest_docs_app

Jest pewny podział, potrzebujemy pewnych end-pointów.
1. Wchodzisz na stronę i masz opcję logowania lub wypróbowania bez. 
2. Koncepcyjnie pomysł mam taki że :
- jeśli wybieramy logowanie to wszystko zachowuje się jak dotychczas
- jeśli wybieramy bez to w głównym `state` aplikacji ustawiamy wartość identyfikującą działanie aplikacji żeby apka wiedziała że korzysta z cookie, np. `use_cookie: true`

```js
Placetag.App = React.createClass({
	mixins: [ Router.State, Router.Navigation],
	getInitialState: function(){
		return {
			places : [],
			mode : 0, //show_mode: 0, create_mode: 1, find_mode: 2, geolocation_mode: 3
			new_marker_position : {}, // lat : 0, lng : 0
			map_center_coords : {},
			found_coords : {},
		};
	},
``` 
3. Kolejnym krokiem jest przerobienie `model.js`, tak aby przy zapytaniu wiedziało czy robi zapytanie na serwer czy do cookie zapisuje coś. 
Np. tak wygląda operacja dodawania miejsca. Podajemy tylko form-data i nic więcej, bo ta metoda jest od razu przystosowana do wykonywania zapytania na serwer. Można by ją podrasować dodając opcjonalny parametr, np. który byłby zczytany z głównego state'a. przykładowo wspomniane `use_cookie: true`
Wtedy zamiast:
`Dispatcher.addPlace(fd);`
można dać
`Dispatcher.addPlace(fd, this.props.use_cookie);`

Wtedy false -> znaczyło by rzuć na serwer, a jeśli byłoby true, obsłuż to przez cookie.
4. Generalnie w pluginie jest objaśnione jak łatwo korzystać tych "reactowych" cookiesów.
5. Dużym wyzwaniem jest tak budowanie obiektu zapisywanego w cookie, aby symulował to co zwraca sealiousowe API, aby nie trzeba było przerabiać części kodu obsługujące miejsca.
Ale to nie jest aż tak trudne jakby mogło się wydawać.

Co więcej ten task jest powiązany z rejestracja/logowanie w reactcie, bo to też potrzebujemy przepisać do Reacta. Logowanie musisz być obsłużone przez qwesta a nie jquery jak to się dzieje teraz.
Rejestracja po utworzeniu konta, nie może zwracać sealiousowej odpowiedzi, tylko powinna to obsłużyć wyświetlić w frontendzie ładny komunikat z odnośnikiem etc.

**Comment by debian-sh** [comment]
Ok rozwiązanie jest ok, ale robimy:
`this.state.is_demo`

i korzystamy z localStorage ← nie znam się na tym temacie

**Comment by debian-sh** [comment]
Trochę temat się utrudnia z działającym logowaniem.

**Comment by debian-sh** [comment]
Przetrzymywanie obiektu w pojedynczym kluczu localStorage http://stackoverflow.com/questions/19174525/how-to-store-array-in-localstorage-object-in-html5

**Comment by debian-sh** [comment]
Nie róbmy tego to nie ma najmniejszego sensu
