### ISSUE TITLE
Dodanie captchy podczas rejestracji

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#124]
Użyć api Google'a: https://www.google.com/recaptcha 
a potem wrzucić całość w Reacta: https://github.com/appleboy/react-recaptcha

**Comment by debian-sh** [comment]
Raczej do rejestracji a nie logowania :)

**Comment by modliszka** [comment]
Rzeczywiście (y)

**Comment by debian-sh** [comment]
Ok rozumiem, że Ty zajmujesz się pierwszym podtaskiem, a ja to później spróbuje dokleić w reactcie?

**Comment by modliszka** [comment]
Mogę obie rzeczy, o ile logowanie będzie już przerzucone do reacta :)

**Comment by debian-sh** [comment]
właśnie dzisiaj będę jeszcze siadać do tego, ale raczej nie skończę na dzisiaj

**Comment by debian-sh** [comment]
Nie ma co się męczyć z tym pluginem, zobacz to :)
https://github.com/dozoisch/react-google-recaptcha

**Comment by modliszka** [comment]
Jak mam umieścić w dependecies plugin do serwera (https://github.com/modliszka/sealious-www-server), skoro on jest pośrednio wykorzystywany?
Chyba bym jeszcze musiała zrobić fork na rest-channel.

**Comment by debian-sh** [comment]
Przeglądałem to, raczej sealious poprawnie zrobi `require` jak w `package.json` wskażesz swojego forka. Nie myślę aby była potrzeba robienia forka na `sealious-rest-channel`

**Comment by debian-sh** [comment]
Czy wszystko z twojej strony jest zakończone? :) w tym issue?

**Comment by modliszka** [comment]
Raczej tak, ale nie zamykam issue, dopóki nie przetestuję gdy całość będzie w wersji 0.13.x

**Comment by modliszka** [comment]
Sprawdzone na 0.13.x i działa. Zamykam.
