### ISSUE TITLE
Modyfikacja field type file

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#129]
Nowo przygotowany field type musi odbierać tylko pliki obrazów, musi dokonywać operacji resize() i zapisywać dwa pliki (miniaturka + zmniejszony oryginał). Następnie wszystko zwracać jako obiekt z dwoma właściwościami.

**Comment by madjer22** [comment]
Po stronie klienta androidowego rozwiazanie satysfakcjonujace

**Comment by debian-sh** [comment]
Właśnie zabieram się zobaczymy co z tego wyjdzie

**Comment by debian-sh** [comment]
Ok działa trzeba tylko dograć skalę z jaką ma się zmniejszyć plik
