### ISSUE TITLE
Rejestracja użytkownika - schemat do wdrożenia

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#131]
Schemat rejestracji powinien wyglądać tak (TODO):
- [ ] Dodanie do zasobu user emaila (back-end)
- [ ] Przy rejestracji preambuła/oświadczenie odnośnie emaila (front-end)
- ~~Jeśli podamy maila, to user powinien otrzymać maila z informacją (username oraz password) na podanego maila. (back-end)~~
- [ ] Wyspecyfikować adres w rest api do resetowania hasła, żądanie które idzie na taki adres powinno wysłać maila resetującego hasło (back-end)
- [ ] Po kliknięciu w link resetujący powinien załadować się jakiś komponent do resetu hasła. (back-end/front-end)

<skopiowałam to ze slack'a jbc>

**Comment by debian-sh** [comment]
Pierwszy task w tym issue był zasygnalizowany tutaj https://github.com/Sealious/sealious/issues/197

**Comment by debian-sh** [comment]
Pierwszy task w tym issue był zasygnalizowany tutaj Sealious/sealious#197
@modliszka - proszę Cię zajmij się punktami 1,3,4.
@Porkite punkt 2 - fajnie gdybyś przygotował treść takiej polityki prywatności
Ja wykonam punkt 5, kiedy będzie wszystko gotowe

**Comment by debian-sh** [comment]
https://trello.com/c/TtIknSXZ/13-enable-extending-resource-type-for-users

**Comment by modliszka** [comment]
Wyślesz mi zapro do trello? Bo nie mogę znaleźć maila (a nie rejestrowałam się chyba jeszcze)

**Comment by debian-sh** [comment]
Wysyłałem we wtorek na nikipedia66@gmail.com

**Comment by debian-sh** [comment]
Rejestrację z mailem zróbmy o ile starczy czasu.

**Comment by debian-sh** [comment]
Na razie zamykam. @modliszka jeśli zabierzesz się za te issue otwórz je.

**Comment by modliszka** [comment]
Lepiej żeby było otwarte, bo mogę o tym zapomnieć, że jest to do zrobienia
