### ISSUE TITLE
Wyświetlanie komunikatu po rejestracji

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#136]
I pozmienianie domen do skryptu z google, bo znalazłam jeszcze parę miejsc z nim, to zmienię je/usunę odwołanie.

**Comment by modliszka** [comment]
@debian-sh Czy da się jakoś w react'cie "odłączyć" to, co jest w require? Bo nadal sypie mi błędami związanymi z niezgodnością domen. Myślę, że na stronie z mapą nadal widoczny jest `react-google-recaptcha`, który się odwołuje do `https://www.google.com/...` i cokolwiek nie kliknę na menu to sypie błędem:

     Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "http://localhost".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

**Comment by debian-sh** [comment]
Wybacz ale nie rozumiem pytania co "odłączyć"? w require?

**Comment by modliszka** [comment]
Z tego co u siebie widzę, na stronie z mapką ciągle jest używany `react-google-recaptcha`, który ma odnośniki do `https`, a to przy każdym zdarzeniu powoduje, że są błędy w konsoli. I tak myślałam, czy jest możliwość użycia tego pluginu tylko podczas rejestracji, a potem, żeby tego nie było w kodzie? Nie wiem jak inaczej wytłumaczyć.

**Comment by debian-sh** [comment]
Zaraz po co ten https? Przecież nie mamy żadnego szyfrowania

**Comment by debian-sh** [comment]
Wyświetlanie komunikatu zrobię w sweetalercie ale po przepisaniu tego modułu do oddzielnego pliku a nie wołanie metod swal wszędzie w interfejsie
