### ISSUE TITLE
Poprawki w RegistrationBox i captcha

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#142]
* brakuje ukrywania przycisku "sign up" do momentu tapnięcia w captche,
* aktualnie można kliknąć w "sign up" i przeskakujemy do okna logowania, niestety dlatego że serwer zwraca success bez potwierdzonej captchy, powinien jakiegoś errora puścić
```js
 { method: 'POST',
  uri: 'https://www.google.com/recaptcha/api/siteverify',
  form: 
   { secret: '6LcHiw8TAAAAAINeXw8BgrYok_8gc7YLX_ToBPq3',
     response: '' },
  headers: { 'content-type': 'application/json' } }
23:17:42.121 - info: 	POST /api/v1/users
			from: 127.0.0.1, mime: application/x-www-form-urlencoded
			result: success!
```
* username fajnie gdyby był przekazany do komponentu logowania, ale to nie jest wymagane

**Comment by modliszka** [comment]
Zrobione w `sealious-www-server`: po kliknięciu w "sign up" jeśli nie ma zaznaczonej captchy, jest zwracany komunikat (błąd 403) - trzeba jeszcze zwrócić odpowiedni komunikat użytkownikowi

**Comment by debian-sh** [comment]
Dokończę to.

**Comment by debian-sh** [comment]
Ok nie ukrywamy przycisku, tylko wyskakuje popup jeśli username lub password jest niezgodny z regexem. Dodatkowo jeśli nie ma zaznaczonej captchy to rzucamy alert o brak zaznaczenia :)
