### ISSUE TITLE
Dodać pole "country" do obiektu wysłanego na serwer 

### ISSUE THREAD

**Issue by madjer22** [debian-sh/Placetag#146]
Dotyczy operacji dodania miejsca zakończonej sukcesem

**Comment by debian-sh** [comment]
Poprawiłem tytuł, ok.

**Comment by debian-sh** [comment]
* brak zwracania kraju w geocoderze
* brak dodawnia wartości kraju przy dodawania miejsca w komponencie PlaceAdd

**Comment by modliszka** [comment]
Pull request ze zmianami: https://github.com/debian-sh/Placetag/pull/149

**Comment by modliszka** [comment]
@madjer22 sprawdź, czy działa tak, jak chciałeś
