### ISSUE TITLE
Leaflet - szukanie miejsca na mapie

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#15]
Znaleźć api, które będzie umożliwiało w miarę dokładne wyszukiwanie miejsc na mapie.

Przykłady:
http://wiki.openstreetmap.org/wiki/Nominatim
http://stackoverflow.com/questions/17726177/can-i-use-openstreetmap-nominatim-reverse-geolocation-api-in-a-commercial-app
http://nominatim.openstreetmap.org/search.php?q=pozna%C5%84%2C+stefana+batorego+79&viewbox=16.91%2C52.47%2C16.92%2C52.46

http://developer.mapquest.com/pl/web/documentation/plugins/leaflet/v1.0/geocoding

**Comment by debian-sh** [comment]
Może skorzystajmy z API Here
http://developer.here.com/api-explorer#geocoder
muszę tylko sprawdzić limity

**Comment by debian-sh** [comment]
Nominatim od OSM też daje radę
http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=wilkowo+polskie+przemyslowa+3


```json
[
{
"place_id": "2569789994",
"licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
"osm_type": "way",
"osm_id": "324350002",
"boundingbox": [
"52.0646025",
"52.064742",
"16.4334408",
"16.4336552"
],
"lat": "52.06467225",
"lon": "16.433548",
"display_name": "3, Przemysłowa, Wilkowo Polskie, gmina Wielichowo, powiat grodziski, województwo wielkopolskie, 64-032, Polska",
"class": "building",
"type": "yes",
"importance": 0.201,
"address": {
"house_number": "3",
"road": "Przemysłowa",
"village": "Wilkowo Polskie",
"county": "gmina Wielichowo",
"state": "województwo wielkopolskie",
"postcode": "64-032",
"country": "Polska",
"country_code": "pl"
}
}
]
```

**Comment by debian-sh** [comment]
Zamykam, dalsze pracę nad tym taskiem w https://github.com/debian-sh/Placetag/issues/22
