### ISSUE TITLE
Poprawa wartości zwracanych z geocodera

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#151]
* Trzeba się zastanowić czy nie dopisywać do wyszukanego miejsca "Droga" kiedy `address` ma tylko wartość liczbową.

![selection_003](https://cloud.githubusercontent.com/assets/5663277/11146081/6054a308-8a0b-11e5-9d21-ea00826c294d.png)

```js
Object {name: "", address: "5", city: "Jarogniewice", latitude: "52.1517821", longitude: "16.6853931"}
```

Co sądzisz?

* Po drugie są miejsca dla, których nie mamy ustalonej nazwy po wyszukaniu, trzeba to też jakoś zgrabnie obsłużyć

![selection_004](https://cloud.githubusercontent.com/assets/5663277/11146147/dcfa4c96-8a0b-11e5-8811-6a9a826bf283.png)

**Comment by modliszka** [comment]
Standardowo w pierwszym przypadku stosuje się wtedy miejscowość + nazwa ulicy. Pytanie czy w takim przypadku nic się nie posypie (mam nadzieję, że nie; sprawdzę, dam znać).
W drugim - bym musiała popatrzeć bardziej na zwracane jsony, ale wydaje mi się, że najlepiej będzie, jak będą wrzucane nazwy miejscowości w nazwę miejsca w takim przypadku.

**Comment by debian-sh** [comment]
* Ok
* Dobry pomysł

W takim razie czekam na feedback :)

**Comment by modliszka** [comment]
Poprawiłam dwie powyższe rzeczy na branchu: issue#151_geocoder_improvement

Jedno mi nie pasuje w wyświetlanych danych. Chodzi mi mianowicie o to, że po nazwie ulicy i ewentualnym numerze budynku brakuje przecinka przed nazwą miejscowości.
Próbowałam poprawić to w reactie, ale coś mi nie trybiło, więc może @debian-sh spojrzysz na to i jeśli wiesz gdzie można, to poprawisz to?

**Comment by modliszka** [comment]
https://github.com/debian-sh/Placetag/pull/159
zmienione polskie komentarze na angielskie
