### ISSUE TITLE
Strona startowa

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#154]
Do przygotowania:
* hasła reklamowe o aplikacji które umieścimy przy ikonkach na stronie startowej
* ikony do tych haseł
* ~~flatowy marker, który użyję do zrobienia naszego logo~~
* hasła reklamowe a bardziej zalety do umieszczenia obok telefonu na stronie
* zastąpienie białego Nexusa 5 czarnym na stronie (grafika musi mieć te same wymiary co aktualna)
* przygotować treść preambuły do zakładania konta z mailem (treść dotycząca tego że użytkownik wyraża zgodę na przetwarzanie jego adresu mailowego)

Wszystkie rzeczy proszę zamieść na slacku.

**Comment by Porkite** [comment]
oks. Rozumiem, że wszystko pl.

**Comment by debian-sh** [comment]
Tak wszystko po PL :)

**Comment by Porkite** [comment]
a co z regulaminem korzystania z serwisu?

**Comment by debian-sh** [comment]
Nie zastanawiałem się nad tym, patrząc ze strony użytkownika. Otrzymuje konto po pomyślnej rejestracji,  dodaje miejsca (prywatnie), może sobie zashareować jakieś miejsce, ale zobaczą to tylko Ci którzy są z nim powiązani w jakiejś społeczności, która nie należy do naszego produktu. Zatem chyba nie ma sensu tworzyć regulaminu. Chyba że masz jakieś istotne wskazania dla których powinien on powstać. Może w takim regulaminie powinniśmy poinformować użytkownika o wykorzystaniu emaila, cookies i o tym że aplikacja jest darmowa. hm? :)

**Comment by Porkite** [comment]
Wydaje mi się, że regulamin jest obowiązkowy, ale trzeba o tym porozmawiać z Marciniakiem. Na razie mogę opisać użytkowanie serwisu i politykę prywatności w ramach skróconego regulaminu.

**Comment by debian-sh** [comment]
Ok to zróbmy tak, o temat regulaminu zapytamy go w najbliższym czwartek, a do tego czasu popracuj nad pozostałymi punktami.

**Comment by debian-sh** [comment]
Ok, z preambułą poczekamy na działający mechanizm z mailem. Na razie zamykam
