### ISSUE TITLE
Popup nad markerem

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#165]
Dodać wyświetlanie nazwy miejsca nad markerem.

Jak zrobić popup
http://leafletjs.com/examples/quick-start.html#working-with-popups

Wyświetlaniem markera zajmuje się MarkerComponent
https://github.com/debian-sh/Placetag/blob/dev/src/js/components/marker.jsx

Fajnie gdyby popup wywoływał się na event click lub hover nad markerem, oczywiście click w inny marker musi spowodować schowanie poprzedniego.

Fragment eventu click markera
```js
		.on('click', (function(event) {   
			document.location.hash = "/place/"+this.props.place.id;
		}).bind(this))
```

**Comment by modliszka** [comment]
#167
