### ISSUE TITLE
Ikonka do udostępniania miejsca przez Twittera

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#166]
Do zrobienia, tak jak na Fb lub Gmaila

**Comment by Porkite** [comment]
się robi

**Comment by modliszka** [comment]
Zmień tylko kolor w css'ie i będzie ok. :)
Ścieżka do css: `.\public\css\style.css`
linijka 665 (`.icon-react-share-twitter:hover`) -> `background-color`
