### ISSUE TITLE
Rejestracja bez captchy

### ISSUE THREAD

**Issue by madjer22** [debian-sh/Placetag#170]
Z uwagi na brak mechanizmów reCaptcha 2.0 dostępnych pod innymi platformami, potrzebna jest możliwość rejestracji bez captchy.

**Comment by debian-sh** [comment]
Może zróbmy token, który ominie captche i zweryfikuje poprawność po username?

**Comment by madjer22** [comment]
Może tak być, ustalmy algorytm generowania tokena.

**Comment by debian-sh** [comment]
hmm, trzeba by zrobić tak że przychodzi zapytanie które nie ma prawdziwego response'a od google to wtedy weryfikowany jest czy istnieje request.payload.token taki który odpowiada algorytmowi.

Można by wysłać token zrobiony z username'a i puścić to przez jakiś algorytm szyfrowania np. md5 albo sha1?

**Comment by madjer22** [comment]
Algorytm przerzućmy na priv

**Comment by debian-sh** [comment]
Ok, to wezmę www-server i dopiszę sprawdzanie, tokenu

Zatem albo będziemy wysyłać username, password, response, a poza klientem webowym, będzie generowany token po sha1 i wysłany wraz z passami.

**Comment by debian-sh** [comment]
Ok, wrzuciłem zmiany na serwer możesz przetestować czy działa? W postmanie przechodzi

**Comment by madjer22** [comment]
Działa :)

**Comment by debian-sh** [comment]
Ok jak coś to otwórz issue, będzie trzeba później domergować.
