### ISSUE TITLE
Zidentyfikowane problemy pod różnymi przeglądarkami

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#182]
Windows 7 - Internet Explorer 11

* ~~problem z dodawaniem miejsc bez zdjęcia~~
* ~~problem z wyszukiwaniem miejsc~~
* ~~brak obsługi ES6 dla komponentu Tagów~~
* ~~zły padding w tagu `<select>`~~
* znikający` background-image` w `react-icon` skrajnie prawy
* problem z zapisywaniem zlokalizowanego miejsca
(Z jakiegoś dziwnego powodu do serwera nie docierają wartości latitude & longitude)

---------------------------------------

OSX - Safari 8/9
* ~~zły padding w tagu `<select>`~~
* ~~brak logo w powitaniu sweetalertowym w SharedPlace~~

*****

**Comment by modliszka** [comment]
Windows 10 - Edge
* Brak markerów (nie pojawia się ten zielony przy dodawaniu)
* Nowe miejsce nie chce się dodać (ciągle jest pasek postępu, nie ma sweet alerta o dodaniu)

**Comment by debian-sh** [comment]
Brak markerów ogólnie czy tylko nowy od dodawania? Prawdopodobnie źle komunikuje się Leaflet z edge i nie może tam wrzucić svg, trzeba zrobić testy z png na szybko podmienionej grafice

**Comment by debian-sh** [comment]
Brak markerów tylko pod Edge trzeba czekać na aktualizację stable biblioteki Leaflet do 1.0.0
