### ISSUE TITLE
Leaflet - wyświetlanie dymku przy markerze

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#19]
Czy mamy możliwość wyświetlenia przy markerze jakiegoś tekstu w formie textboxa? Jeśli tak to prawdopodobnie przyda się nam taka implementacja.

**Comment by modliszka** [comment]
Tak, jest możliwe takie coś :)
Sprawdź sobie:

      L.marker([ latlng.lat, latlng.lng ])
             .addTo(map)
             .bindPopup('<strong>' + best.city + ', ' + best.street + '</strong><br />is located here.')
             .openPopup();

dokumentacja: http://leafletjs.com/examples/quick-start.html

**Comment by debian-sh** [comment]
Spoko na razie nie zamykam, wykorzystamy to później :+1:
