### ISSUE TITLE
Dostęp do użytkowników

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#196]
Chyba sprawa backendu - trzeba zabezpieczyć się od możliwości wejścia na link z zasobem użytkownicy przez jakąkolwiek osobę.

**Comment by debian-sh** [comment]
Zanim założysz issue to sprawdź czy problem istnieje
http://placetag.pl/api/v1/users

**Comment by modliszka** [comment]
No to sobie sam sprawdź inny link zanim skomentujesz (ew. spójrz na slacka)
http://placetag.pl/api/v1/user

**Comment by debian-sh** [comment]
Skąd istnieje zasób `user`? Bo zawsze korzystaliśmy z `users` i taki zasób schowałem.

**Comment by modliszka** [comment]
Nie mam pojęcia, testowałam dostępność zasobów, to takie coś się pokazało - i tam na pewno są aktualne passy.

**Comment by debian-sh** [comment]
Poszedł task: https://trello.com/c/2WfbY6pV/45-access-to-resource-type-users-by-paths-users-and-user

**Comment by debian-sh** [comment]
https://github.com/debian-sh/Placetag/pull/208
