### ISSUE TITLE
[UI] Zaprojektowanie wyglądu markera dla mapy

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#2]
Myślę że marker powinien iść stronę takich kolorów `#285069 #547880 #45ADA7 #008080`.
Dlatego taska tworzymy nowy branch o nazwie "issue#2", projekt markera należy umieścić w nowym katalogu "CI".

**Comment by Porkite** [comment]
Zostały dodane wcześniej uzgodnione markery, issue do zamknięcia

**Comment by debian-sh** [comment]
Marker do małej poprawki, generalnie proszę Cię o wyeksportowanie ostatniego markera do plików svg i png z brancha docs i wycentrowanie na takiej zasadzie aby dolny piksel w którym zaczyna się grafika był dokładnie na środku, usunięcie cienia, odpowiednia wysokość img w png to 36px. Po tym zamykamy issue ;)

**Comment by Porkite** [comment]
poszły dwa pomysły do katalogu final, ten z dziurką też fajny ;).
