### ISSUE TITLE
Dodać popup o korzystaniu z cookies

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#206]

**Comment by debian-sh** [comment]
@Porkite Sprawdź czy informacja o cookies wystarczy, że jest w regulaminie czy potrzebujemy dodatkowego boxa?

**Comment by Porkite** [comment]
Podstawa prawna mówi, że info o ciasteczkach musi być widoczne i zrozumiałe dla czytelnika, nie określa jednoznacznie, czy dozwolone jest przetrzymywanie tej informacji w regulaminie. Prawda jest taka, że nikt nie czyta regulaminów, więc na wszelki wypadek taką informację trzeba byłoby umieścić. Widzę dwa wyjścia:
1. Można zrobić jak każda inna strona popup z info, ale żeby nie było rażące, można je umieścić jako cienka stopka z możliwością zamknięcia.
2. Podczas pierwszego zalogowania lub rejestracji zapodanie na twarz informacji o ciasteczkach którą trzeba zaakceptować + info w regulaminie.
Osobiście nie widziałem, żeby jakaś strona wykorzystywała drugie podejście, chociaż facebooki google, czy inne tweetery tak może robią

**Comment by debian-sh** [comment]
Zrobię 1.
