### ISSUE TITLE
Nominatim - ściąganie informacji o miejscu

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#22]
Potrzebna jest funkcja, która jako parametr przyjmie stringa z adresem wpisanym przez użytkownika.
Zapytaniem ajaxowym w jquery powinna ściągać JSONa i wyciągać z niego dane między innymi o pozycji latitude i longitude. Zapytanie ajaxowe należy kierować na następujący adres:

przykład zapytania dla Wilkowo Polskie, ul. Przemysłowa 3

http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=wilkowo+polskie+przemyslowa+3

Strukturę JSONa przedstawiłem w https://github.com/debian-sh/Placetag/issues/15

Musi zwracać obiekt o następującej strukturze (odpowiadający strukturze naszego zasobu REST API zdefiniowanego w `main.js`).

```javascript
var place = {
	'latitude' : 52.471226841873495,
	'longitude' : 16.904611587524414,
	'street' : "string",
	'city' : "string"
};
```

**Comment by debian-sh** [comment]
Jak stoisz z zadaniem?

**Comment by debian-sh** [comment]
Gotowe?

**Comment by Porkite** [comment]
prawie gotowe, mam problem z wydobyciem danych do obiektu place, ale do jutra się z tym uporam

**Comment by debian-sh** [comment]
Wyciągasz dane z jsona po przez zagnieżdżone klucze. Jak wyciągasz JSONa z jquery do zmiennej to następnie trzeba odwoływać się po kluczach tak jak w tym przykładzie

http://stackoverflow.com/questions/6329810/how-to-get-following-json-parameters-values-with-javascript

na koniec tworzysz
```javascript
var place = {
    'latitude' : zmienna_1
    'longitude' : zmienna_2
    'street' : zmienna_3
    'city' : zmienna_4
};
```

**Comment by Porkite** [comment]
zerknij na to co wrzuciłem

**Comment by debian-sh** [comment]
jak gotowe to przenieś ten plik do jakiegoś katalogu np libs i załóż pull 
requesta do mojego brancha issue#23-dev-model

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
- Nie przypisujesz miasta, jest undefinded.
```javascript
get("Luboń, Mickiewicza 2")
undefined
jquery.js:4 XHR finished loading: GET "http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=lubon+mickiewicza+2".send @ jquery.js:4m.extend.ajax @ jquery.js:4m.(anonymous function) @ jquery.js:4m.extend.getJSON @ jquery.js:4get @ getplace.js:33(anonymous function) @ VM153:2InjectedScript._evaluateOn @ VM36:895InjectedScript._evaluateAndWrap @ VM36:828InjectedScript.evaluate @ VM36:694
getplace.js:59 szerokość = 52.34662
getplace.js:60 długość = 16.87593
getplace.js:61 ulica = Adama Mickiewicza 2
getplace.js:62 miasto = undefined
```

-  Funkcja
```javascript
function sampleCallback(outputData)
``` 
jest zbędna, wystarczy zrobić `console.log(place);` w ciele `var json = $.getJSON( url+paramplus, function( data )`

-  W następnym kroku będziemy robić emitty z tą zmienną. Zainstaluj sobie jeszcze HTML/CSS/JS Prettify do sublime'a żeby poprawić wcięcia. I zrób git fetch na branchu dev-model, następnie domerguj dev-model do swojego brancha, a swój plik wrzuć do `placetag-app/public/js/`, wyślij zmiany na swój branch i zrób pull requesta do dev-model.

**Comment by Porkite** [comment]
przepisywanie miasta poprawione, okazał się, że miasto może być przechowywane w trzej miejscach: address.village, address.city albo address.town. Podobnie też jest z ulicą.

**Comment by debian-sh** [comment]
Ok jak przetestujesz kod zrób pull requesta wedle wskazówek opisanych wyżej

**Comment by debian-sh** [comment]
Gotowy kod:

https://github.com/debian-sh/Placetag/blob/dev-model/placetag-app/public/js/getplace.js

**Comment by Porkite** [comment]
Musimy zwracać listę miejsc w celu wyświetlenia kilku propozycji po zapytaniu.

**Comment by debian-sh** [comment]
Lista obiektów^

**Comment by debian-sh** [comment]
I jak gotowe?

**Comment by debian-sh** [comment]
Przerzuć jeszcze regexy do tablicy i leć to forem.

**Comment by Porkite** [comment]
ok, siedzi zmieniona funkcja

**Comment by debian-sh** [comment]
Ok jak na twoim branchu odnośnie issue to załóż pull requesta do dev-model ;)

**Comment by modliszka** [comment]
Zmiany dodane na dev-model. Poproszę o sprawdzenie, czy taki sposób wyświetlania danych jest wystarczający?

**Comment by debian-sh** [comment]
Jest ok braknie tylko pan.To i ładnie reprezentacji po wybraniu miejsca jakaś kropka musiałaby się pojawić na ulicy coś w stylu koła.

**Comment by modliszka** [comment]
Czy nie powinniśmy zrobić taki use-cse, że jak ktoś sobie wyszuka miejsce, to będzie chciał je od razu dodać? Bo tak się zastanawiam, do czego my używamy wyszukiwanie miejsca. 
Znajdziemy je i... - co właśnie? Wyświetlimy listę propozycji, porobimy kropki dla tych miejsc na mapie i myślę, że jak ktoś będzie dane miejsce chciał dodać sobie, to powinniśmy w którymś miejscu zrobić jakiś 'ptaszek' albo 'plusik' oznaczający pokazanie dodawanie nowego miejsca z przekazanymi danymi.

What do u think?

**Comment by debian-sh** [comment]
Myślę tyle, że się nie rozdwoje :< zrobimy plusik z metodą store.add




*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl
Sent from Xubuntu 14.04

2015-06-06 13:08 GMT+02:00 modliszka <notifications@github.com>:

**Comment by debian-sh** [comment]
Przenosimy usera do danego miejsca jeśli zapytanie zwróciło jeden wynik, w przypadku większej ilości user otrzymuje listę a po kliknięciu w miejsce, przenosimy go do tego miejsca :) Kwestie plusików etc rozwiążemy później :)
