### ISSUE TITLE
Brak informacji o kategorii w widoku w komponentach SharedPlace oraz PlaceShare

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#222]

**Comment by modliszka** [comment]
Brak tej informacji wynika z nieprzekazanej kategorii w linku czy z jakiegoś innego powodu?

**Comment by debian-sh** [comment]
Nie jest wyświetlona w widoku.

**Comment by debian-sh** [comment]
https://github.com/debian-sh/Placetag/commit/8f53cfe014037ecb4c0f67c99ec4597b71fdee97
