### ISSUE TITLE
Dodanie możliwości użycia znaków specjalnych w haśle

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#227]
1. Zmodyfikować regex.
2. Przetestować na regex101.com.
3. Modyfikacja zwracanego komunikatu (przy błędnej weryfikacji hasła). 
4. Rozdzielenie alertów względem rodzajów komunikatu.

**Comment by debian-sh** [comment]
https://github.com/debian-sh/Placetag/pull/228
