### ISSUE TITLE
Leaflet - centrowanie mapy względem wybranego markera, zaznaczanie po przez id, odznaczanie markerów

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#24]
Podczas wybrania danego markera z listy chcielibyśmy centrować mapę, tak aby zaznaczony marker znajdował się dokładnie na środku interfejsu.

Funkcja wykonująca te zadanie musiałby jako parametr przyjmować obiekt markera, albo współrzędne.

Dodatkowo potrzebujemy funkcji, dzięki której możemy wywołać zaznaczenia markera. Bo taka rzecz będzie potrzebna do komponentu reactowego, aby w momencie wybrania miejsca z listy tagów, dany marker zaznaczył się a mapa wycentrowała względem niego.

**Comment by modliszka** [comment]
http://stackoverflow.com/questions/12735303/how-to-change-the-map-center-in-leaflet
Jest na to funkcja `map.panTo(new L.LatLng(40.737, -73.923));`
Więc jeśli chcemy zaznaczyć markera klikając na tag na liście i ustawić go jako centrum mapy, to do funkcji centerMapToMarker(marker_id) przekazujemy tylko id wybranego markera.

**Comment by debian-sh** [comment]
Wyczyść bazę i zobacz czy dodają Ci się nowe markery. Czytaj pododawaj kilka markerów przez postmana i zobacz czy Ci się wyświetlają w interfejsie, bo mi magicznie się przestały pokazywać na mapce. :< Nie wiem czy to problem po aktualizacji sealious'a do wersji 0.3+

**Comment by modliszka** [comment]
Rozumiem, że póki co Sealiousa nie mam aktualizować?

**Comment by debian-sh** [comment]
Generalnie najpierw zobacz co się stanie przed aktualizacją, kiedy wyczyścisz bazę i dodasz nowe markery.

**Comment by debian-sh** [comment]
Ok wszystkie hotfixy są zapuszczone, możesz wprowadzić zmiany odnośnie centrowania i zaznaczania.

**Comment by debian-sh** [comment]
Potrzebujemy jeszcze funkcji do zaznaczania, trzeba pamiętać uprzednio zaznaczony marker po id i w momencie wywoływania funkcji changeSelectedMarker(marker_id) odznaczamy poprzedni zaznaczamy nowy po przez podanie marker_id.

**Comment by modliszka** [comment]
Ale to już mamy? Zmienna `oldLayer` zapamiętuje całego markera, który jest obecnie zaznaczony.

**Comment by debian-sh** [comment]
Ok jeśli zmieniam jego pozycję to ma zawartą aktualna wartość pozycji czy 
tylko tę z zaznaczenia?

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by modliszka** [comment]
Dodałam teraz jeszcze funkcję do odznaczanie miejsca (założyłam jest jedno zaznaczone miejsce).

**Comment by debian-sh** [comment]
Otwieram do wdrożenia zmiany na nowym branchu

**Comment by debian-sh** [comment]
Umknęła nam funkcja do zaznaczania po wskazanym id, dopisałem ją.

```javascript
//odznaczanie zaznaczonych markerów
function uncheckCurrentMarker(){
}

//zaznaczanie markera po id i odznaczenie pozostałych
function checkNewMarker(marker_id) {
}

//centrowanie mapki względem wybranego markera
function centerMapToMarker(marker_id) {
}
```

**Comment by debian-sh** [comment]
Wszystko w temacie, działa ładnie!
