### ISSUE TITLE
Nodemailer - pakiet do wysyłania maili

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#25]
Przetestować ten pakiet, zobaczyć jak działa i zdać relację. Fajnie byłoby go wykorzystać do shareowania miejsca :)

https://www.npmjs.com/package/nodemailer

**Comment by Porkite** [comment]
jutro przyjrzę się temu bliżej

**Comment by modliszka** [comment]
Moje sugestie na tę chwilę są takie:
jak mamy przycisk 'share' to wyświetlmy ikonki ze sposobami share'owania, czyli np. Gmail i kółko ze znakiem ogólnym do wysyłania poczty. Wtedy jak ktoś kliknie Gmail, to go od razu przekieruje do poczty gmail, bo taką fukncję raz dwa mogę zaimplementować. 
Z funkcją dowolnej poczty nie powinno być problemu, jedynie użytkownik będzie musiał podać swojego maila oraz hasło do weryfikacji. 

Mogę w najbliższym czasie liczyć, że takie coś ze strony frontendu powstanie?

**Comment by debian-sh** [comment]
Po prostu przygotuj gotowy kod obsługujący feature np z konsoli a wtedy 
podepniemy to do frontu

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by modliszka** [comment]
Poniżej przesyłam funkcję, która otwiera okno do wysyłania maila na Gmailu (z wypełnionymi polami). Na razie napotkałam na taką trudność (w node_mailerze), jaką jest wysyłanie maila na coś innego niż Gmail.
```
var send_gmail = function(to,subject,message){
    var str = 'http://mail.google.com/mail/?view=cm&fs=1'+
              '&to=' + to +
              '&su=' + subject +
              '&body=' + message.replace(/\n/g,'%0A') +
              '&ui=1';
    location.href = str;
}

**Comment by debian-sh** [comment]
Do rozpatrzenia później.
