### ISSUE TITLE
React/Leaflet - Dodowanie nowego markera

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#29]
Do zrobienia komponent umożliwiający dodawanie jednego, nowego markera do mapy.

Task ma dwa etapy:
Etap 1

1. Przygotowanie pliku `tag-leaflet.js`, tak aby reagował na zmianę pewnej flagi. 
- Kiedy ona zostanie zmieniona będzie można dodać dokładnie jeden marker na mapę. 
- Kliknięcie w inne miejsce na mapie powoduje przeniesienie tego markera w inne miejsce. 
- Wybranie flagi dodawania nowego markera, powinno odznaczyć dotychczasowy zaznaczony marker.
- Marker zostanie dodany do modelu, kiedy zostanie wciśnięty przycisk dodaj. 

Moniko do testów utwórz sobie nowego brancha, na podstawie brancha dev-model. Do dodawania utwórz sobie button jquerowy wywoływujący funkcję `store.add`.

Etap 2
W tym etapie, napiszę komponent obsługujący ten feature. Obsługujący niezbędne input'y do wysyłania odpowiednich danych do rest api.

**Comment by modliszka** [comment]
Co już jest:
1. Flagę zmieniamy uruchamiając funkcję: `changeMapsEditOption()`.
2. Działa to.
3. Też działa, ale: marker nie jest aktualizowany, a usuwany oraz dodawany jako nowy.
4. Zmiana na brak możliwości edycji spowoduje:
 -odznaczenie zaznaczonego markera,
 -usunięcie niezapisanego markera.

Problemy:
-raz można przenieść markera, potem już nie, bo sypie błędem `TypeError: place_from_store is undefined`.
-tak samo jeśli kliknę na nowo utworzonym markerze, to nie ma już opcji zapisu, jest tylko opcja usunięcia.
-nawet jak kliknę `Zapisz`, to nie zapisuje tego markera.

**Comment by debian-sh** [comment]
Problemy odp:
- problem z przenoszeniem markera i id ustawionym na `undefined` można obejść ładnie i brzydko

- ładnie to wyłączyć dodawanie do store.add, bo prawdopodobnie gdzieś jest zapamiętywany ten `undefined` i później leci get na niego a on nie istnieje, trzeba poszukać tego zachowania w kodzie,
W zależności od flagi funkcji `changeMapsEditOption()` oraz aktualnego `id` powinniśmy wysyłać odpowiedni emit do Reacta

- mój pomysł jest taki że przeanalizujemy kod, zrobimy odpowiednie emity i stworzymy jeden komponent do wyświetlania/edycji/dodawania miejsca, w zależności od odpowiedniego emitu:

- wyświetlenie miejsca
wyświetlimy aktualne zapisane miejsce to możemy realizować kiedy jest ustalone id, leci emit jeśli jest inny niż `undefined` wyświetl dane z modelu,

- edycja miejsca
wyświetlimy możliwość edytowania zapisanego miejsca jeśli klikniemy w button edycja, wtedy wczytamy dane z modelu umieszczając je w odpowiednie inputu,

- dodawanie miejsca
wyświetlimy możliwość uzupełnienia informacji o nowym miejscu jeśli klikniemy w button dodaj miejsce, wtedy wywołamy emit z wartością `undefined`


Myślę że rozwiązując problem tak jak to opisałem powyżej unikniemy błędów z przeciąganiem i klikaniem. Domyślnie przy tworzeniu nowego markera usunąłbym możliwość klikania w niego. 
Zatem użytkownik będzie mógł przeciągać marker po mapie i klikać w inne miejsce na mapie, przez co marker teleportuje się ;)

**Comment by debian-sh** [comment]
Ustaliliśmy jak ogarnąć ten dodawanie, co do emitu o którym wspomniałem będziemy reagować reactem na adres url. Dodawanie nowego markera powinno być autonomiczne, rozdzielne od tego kodu.

```javascript
function createMarker(place) {
    marker = new customMarker([place.latitude, place.longitude], {
            draggable: true,
            id: place.id,
            icon: icon_normal
        })
        //.bindPopup(place.description)  //dodaje dymek nad markerem
        .on('click', function onMapClick(event) {
            document.location.hash = "/places/" + place.id;
            //clickFeature(event);            
            refreshMarkerPosition(event, place.id, false);

            //centrowanie mapy po kliknięciu w marker i jego zaznaczenie
            centerMapToMarker(place.id);
        })
        .on('dragstart', function(event) {
            //document.location.hash="/places/"+place.id;
            clickFeature(event);
            refreshMarkerPosition(event, place.id, false);
            ee.emit("dragstart");

        })
        .on('drag', function(event) {
            var position = refreshMarkerPosition(event, place.id, false);
            //console.log(position);
            ee.emit("marker_drag", position);

        })
        .on('dragend', function(event) {    
            refreshMarkerPosition(event, place.id, true);
            ee.emit("dragend");

        })
        .addTo(map);
    markers_by_id[place.id] = marker;
}
```

Bo jeśli chodzi o przeciąganie markera to wykorzystujemy ten blok do PlaceView.
