### ISSUE TITLE
[UI] Zaprojektowanie loga

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#3]
Moja propozycja:
![selection_008](https://cloud.githubusercontent.com/assets/5663277/6546093/64e716ce-c5a5-11e4-90a8-b9f96b887ca8.png)

Fajnie nadaje się font Lato. Jak dla każdego issue tworzymy nowy branch.

**Comment by debian-sh** [comment]
Spróbuj porobić kilka opcji flat designowych z fontem Lato, Sans Source Pro. Sam logotyp bez znaku.

**Comment by debian-sh** [comment]
Co w temacie?

**Comment by debian-sh** [comment]
![icon_projekty_o](https://cloud.githubusercontent.com/assets/5663277/7408521/b4996ac2-ef1d-11e4-994e-e65b84e68513.png)

a co powiecie na taki kształt? :)

**Comment by debian-sh** [comment]
Podbijam!

**Comment by Porkite** [comment]
Myślę, że jako element loga sprawdzi się bardzo dobrze, ale nie widzę go jako tag na mapie, moim zdaniem jest za gruby ;D

**Comment by debian-sh** [comment]
Myślę że icon tag musi być spójny z logiem zatem spróbuj stworzyć logo. Ja 
zobaczę jak pasuje tag na mapce.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
Albo zrób sobie oddzielnego brancha dodaj marker na mapę i wyślij tutaj 
screenshot

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
I jak testy?

**Comment by debian-sh** [comment]
Co w temacie?

**Comment by Porkite** [comment]
Przecież rozmawialiśmy na ten temat

**Comment by Porkite** [comment]
![test](https://cloud.githubusercontent.com/assets/4449083/7586720/083611b2-f8b0-11e4-879f-cda2d5300ad6.png)

Moim zdaniem nadal najlepiej prezentuje się nasz dotychczasowa ikonka.

**Comment by debian-sh** [comment]
a gdyby z tej nowej stworzyć coś pomiędzy starą a nową. Tzn nowa trochę zwężona?

**Comment by Porkite** [comment]
Myślisz o czymś takim?
![3prop4](https://cloud.githubusercontent.com/assets/4449083/7587973/3be812bc-f8ba-11e4-8099-5a6d952def95.png)

**Comment by debian-sh** [comment]
Tak tak i bez dziurki :)

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Porkite** [comment]
![screen](https://cloud.githubusercontent.com/assets/4449083/7665184/89a2c750-fbac-11e4-815c-6c18a09e82b1.png)
te większe, ale w kolorze niebieskim nie są wcale gorsze

**Comment by Porkite** [comment]
Ale kwestię loga możemy już chyba uznać za zamkniętą.
<img class="alignnone" src="https://cloud.githubusercontent.com/assets/4449083/7665196/05bdcede-fbad-11e4-9438-8f363adcfe44.png" alt="" width="250" height="250" />
<img class="alignnone" src="https://cloud.githubusercontent.com/assets/4449083/7665195/05bb1946-fbad-11e4-836f-d75e99ec3fa4.png" alt="" width="250" height="250" />

**Comment by debian-sh** [comment]
Nowe markery są super, wykorzystamy oba. Bardziej niebieski jako zwykły, a turkusowy jako podświetlony. Jeśli chodzi o logo kształt markera powinien być spójny z nowymi markerami i wtedy będzie finito :+1:

**Comment by Porkite** [comment]
finalne logo zostało wrzucone, issue do zamknięcia.

**Comment by debian-sh** [comment]
Poprawić tylko przestrzenie, czyli zrobić auto crop żeby nie było paddingów-marginesów.

**Comment by Porkite** [comment]
przestrzenie poprawione, logo siedzi w repo.

**Comment by debian-sh** [comment]
Podmień logo na branchu dev-model i zrób pomiary jakimś rulerem czy z każdej strony są idealne paddingi.
