### ISSUE TITLE
UI - ikonki do interfejsu

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#34]
Do zaprojektowania ikonki "miejsc" i "lupy". Tak aby pasowało to do tych napisów i ikonki "hamburgera"

![image](https://cloud.githubusercontent.com/assets/5663277/7502607/702f511a-f43d-11e4-8b9d-92b1bfffbdaf.png)

**Comment by Porkite** [comment]
taka propozycja
![prop2](https://cloud.githubusercontent.com/assets/4449083/7509799/978ed0e8-f495-11e4-9e71-697f00c975df.png)

**Comment by debian-sh** [comment]
ok ale delikatnie mniejsze, muszą być spójne co do wielkości grafiki hamburgera

**Comment by Porkite** [comment]
gotowe ikonki w nowym branchu

**Comment by debian-sh** [comment]
Wrzuć screenshot i załóż pull request do dev-model.

**Comment by debian-sh** [comment]
Co w temacie?

**Comment by Porkite** [comment]
![untitled-12](https://cloud.githubusercontent.com/assets/4449083/7588204/e407a5a6-f8bb-11e4-98b3-0d6659babdb6.png)
*Propozycja podania

wiadomo, kosz i prawdopodobnie znak zapytania będą w innych miejscach

**Comment by debian-sh** [comment]
Super jeszcze ikonkę to zapisu i ikonkę do edycji możesz zrobić.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Porkite** [comment]
czy ikonka zapisu ma być zwykłym plusikiem?

**Comment by debian-sh** [comment]
Plusik, ptaszek albo coś w stylu dyskietki, jeszcze potrzebować będziemy ikonki do shareowania miejsca.

**Comment by Porkite** [comment]
![preview](https://cloud.githubusercontent.com/assets/4449083/7628210/ea099156-fa20-11e4-8832-12d5b1e1b7c4.png)
taka sytuacja

**Comment by debian-sh** [comment]
Na razie ok, super zamykam!

**Comment by Porkite** [comment]
są nowe ikonki do wylogowywania się, zapisywania i miejsc.

**Comment by debian-sh** [comment]
Zostawiam jakby trzeba było coś jeszcze dorobić

**Comment by Porkite** [comment]
![concept](https://cloud.githubusercontent.com/assets/4449083/7783746/209ba5e6-014d-11e5-9df4-351db79fab43.png)
Coś takiego mi chodziło po głowie,
ikonki są próbne.

**Comment by debian-sh** [comment]
Super ale jest jedno zastrzeżenie, każdy z tych markerów musi mieć 
przewidziane podświetlenie oraz kolor ich musisz domieszać do naszego 
bazowego koloru tzn z 3 kanałów zmieniasz np tylko jeden wtedy będzie się 
ładnie wszystko komponować.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Porkite** [comment]
jasne, przedstawiam tu raczej koncepcję, dlatego napisałem. że ikonki próbne.

**Comment by debian-sh** [comment]
koncepcja spoko!



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl

**Comment by debian-sh** [comment]
Ikona aparatu i strzałki w lewo (back)

**Comment by debian-sh** [comment]
Na razie zamykam! :)
