### ISSUE TITLE
REST - Reprezentacja zasobu typu place

### ISSUE THREAD

**Issue by madjer22** [debian-sh/Placetag#37]
Dodać do bazy, aby pojedynczy rekord zawierał:
<b>id, ownerID, name, category, description, status, image, privacy, longitude, latitude, address, city, country, votes, sum, globalRate, myRate</b>

Po dodaniu poproszę też o nazwy wraz z Androidowymi odpowiednikami dla każdej z nich. Niech minimalnym konstruktorem (dla mnie - tzn. na swoje potrzeby będę z takiego minimalnego korzystał) będzie: id + ownerID + name + longitude + latitude + image (stringi wszystko). Chciałbym, aby była też możliwość dodania wraz z description, address, city, country. Votes + sum + globalRate + myRate ustawiam domyślnie na 0.

Kwestia ID do dogadania. Poza tym unikatowym ID jako string, chciałbym też mięć pole ID typu int, które będzie leciało od 0 do n, gdzie jakieś i - oznacza i miejsce danego usera. Ale na ten moment proszę też o dodanie pola o nazwie id, mi to będzie potrzebne do wstawiania tego by nie zmieniać całego mojego kodu. Niech to ID sie generuje samo automatycznie to które jest, a to zwykłe numeryczne id będę ja wstawiał dla siebie

**Comment by debian-sh** [comment]
Pojedynczy dokument reprezentujący zasób `place` zawiera:

```javascript
var places = new Sealious.ChipTypes.ResourceType("places");	
places.add_fields([
	{name: "title",					type: "text"},
	{name: "description",			type: "text"},
	{name: "street",				type: "text"},
	{name: "city",					type: "text"},
	{name: "longitude",				type: "float", required: true}, //52 dlugosc
	{name: "latitude",				type: "float", required: true}  //16 szerokosc
])
```

- Dodatkowo reprezentacja tego zasobu w każdym dokumencie ma:
`id, owner_id` oraz `access_mode`

- Nie potrzebujesz pola typu `privacy` ten feature dostępności danego dokumentu będzie realizowany po przez `access_mode` w późniejszym czasie.

- Kwestia ID, będą to GUIDy, wewnątrz swojej aplikacji możesz interować po każdym obiekcie JSONa i dopisywać mu id.

- Do czego ma być przeznaczone pole `status`?

- Pole `image` będzie polem służącym do trzymania prawdopodobnie adresu url do pliku na serwerze. Docelowo zdjęcie będziesz musiał przesłać, tak samo jak robi to zwykły input w HTMLu. Kod obsługujący został już przetestowany z wykorzystaniem windows phone.

- `title` zostanie zamienione na `name` typu text (string)
- `street` zostanie zamienione na `address` type text (string)
- `category`, `description`, `country` będą typu text (string)

- `votes`, `sum`, `globalRate`, `myRate`, będą polami typu int

- `longitude`, `latitude`, będą polami typu float, ponieważ leaflet ma problem z odczytywaniem stringów i dla niego docelowym typem danych jest float.

- "Po dodaniu poproszę też o nazwy wraz z Androidowymi odpowiednikami dla każdej z nich." Nie rozumiem, dostaniesz info o commicie tutaj i sobie te nazwy potworzysz.

- Minimalne pola jakie są wymagane do utworzenia dokumentu zasobu to `longitude` i `latitude`.
Po utworzeniu dokumentu tak jak wcześniej wspomniałem dodatkowo zostają dodane pola `id`, `owner_id` oraz `access_mode`. To czy wyślesz większą ilość pól zależy od Ciebie.

- Struktura po wdrożeniu będzie następująca

```javascript
	{name: "name",				type: "text"},
	{name: "category",				type: "text"},
	{name: "description",			type: "text"},
	{name: "address",				type: "text"},
	{name: "city",					type: "text"},
	{name: "image",				type: "text"},
	{name: "votes",				type: "int"},
	{name: "sum",				        type: "int"},
	{name: "globalRate",			type: "int"},
	{name: "myRate",				type: "int"},
	{name: "image",				type: "text"},
	{name: "longitude",				type: "float", required: true}, //52 dlugosc
	{name: "latitude",				type: "float", required: true}  //16 szerokosc
```

**Comment by debian-sh** [comment]
Nowa reprezentacja zasobu `place` została dodana i wrzucona na produkcję.
```javascript
var places = new Sealious.ChipTypes.ResourceType("places");	
places.add_fields([
    {name: "name",              	type: "text"},
    {name: "category",              type: "text"},
    {name: "description",           type: "text"},
    {name: "address",               type: "text"},
    {name: "city",                  type: "text"},
    {name: "image",             	type: "text"},
    {name: "votes",             	type: "int"},
    {name: "sum",					type: "int"},
    {name: "globalRate",            type: "int"},
    {name: "myRate",                type: "int"},
    {name: "image",             	type: "text"},
    {name: "longitude",             type: "float", required: true}, //52 dlugosc
    {name: "latitude",              type: "float", required: true}  //16 szerokosc
]);
```
https://github.com/debian-sh/Placetag/blob/dev-model/placetag-app/main.js

**Comment by debian-sh** [comment]
Dopisać pole `{name: "country", type: "text"}`

**Comment by debian-sh** [comment]
Gotowe, zamykam!
