### ISSUE TITLE
Dynamiczne aktualizacje zasobów

### ISSUE THREAD

**Issue by madjer22** [debian-sh/Placetag#41]
Aby aplikacja nie pobierała za każdym razem list wszystkich własnych miejsc danego usera (bo przecież trzyma swoje miejsca w swojej lokalnej bazie danych), przydałby się mechanizm który dla warstwy z poziomu webówki po dodaniu, usunięciu, edycji miejsca, poinformuje o tym użytkownika w aplikacji mobilnej. Ten mechanizm działa z mobilki do webówki, bo wszystko idzie restem, wiec wszystsko co z apki pójdzie, będzie widoczne w webówce (kwestia implementacji).

Przykładowy scenariusz:
Mam 10 swoich miejsc. Wchodze na stronę główna apki, ekran główny, i mam listę miejsc. Kieruje zapytanie do serwera lub nasłuchuje na serwerze, czy wśród tej kolekcji nastąpiły jakieś zmiany (usunięcie, edycja czy dodanie 11 miejsca). Jeśli nastąpiły, pobieram dane z serwera i aktualizuje zasoby we własnej lokalnej bazie danych. Jeśli zmiany nie nastąpiły, nie mam po co marnować transferu, więc nic nie pobieram z sieci, a wyświetlam tylko listę swoich miejsc.

**Comment by debian-sh** [comment]
Bardziej backendowo do rozwiązania. Muszę przemyśleć ten use case.

**Comment by madjer22** [comment]
Tak jak wspomniałem, proponuje konkretny adres na rescie typu
api/v1/changes/idusera

w ktorym bylby json, do ktorego zawsze z apki kierowałbym zapytanie

**Comment by debian-sh** [comment]
Temat nie będzie rozwiązany do końca tego semestru, także na razie skup się na pobieraniu całego JSONa i podmienianiu stanu w aplikacji. Docelowo komunikacja będzie załatwiona po socketcie i będzie wysyłany PUSH do różnych aplikacji, który będzie informował o zmianach podając timestamp ostatniej aktualizacji.

**Comment by debian-sh** [comment]
Wyspecyfkować adres `/api/v1/changes/GUID`, struktura zasobu

```javascript
{
"up": [id1, id2, id3, ...],
"del": [id5, id9 ...],
"id" : 'guid'
}
```

**Comment by debian-sh** [comment]
Zrobię po wykonaniu  issue#44

**Comment by debian-sh** [comment]
Na pewno nie zdążę do przyszłego czwartku. Do pokazu przygotuj wczytywanie całego JSONa z GETa.

**Comment by debian-sh** [comment]
Nie możemy tego wprowadzić z powodu niewydajności tego rozwiązania. Trzeba poczekać do wdrożenia powiadomień na sockety.

**Comment by debian-sh** [comment]
Taka będzie struktura
```javascript
{
"add": id7;id8;
"up": id2;id4;id3;
"del": id10;
"id" : 'guid'
}
```
