### ISSUE TITLE
Leaflet/React - zaznaczanie dwóch markerów

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#49]
![image](https://cloud.githubusercontent.com/assets/5663277/7681110/2b28ea52-fd6d-11e4-9e3c-3fed2e2d8850.png)

Często zaznaczają się dwa markery

**Comment by modliszka** [comment]
Poszedł commit i push, sprawdź czy teraz działa [bo u mnie już działa :D].

**Comment by debian-sh** [comment]
Cały czas przy kliknięciu w marker, a później w kolejny cały czas są podświetlone.

**Comment by debian-sh** [comment]
![image](https://cloud.githubusercontent.com/assets/5663277/7687757/c0933bb0-fd9f-11e4-88f6-2392df951382.png)

**Comment by debian-sh** [comment]
Działa! :)
