### ISSUE TITLE
[backend] Przemyślenie struktury dokumentów w kolekcjach MongoDB

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#5]
Jakie rzeczy chcielibyśmy przechowywać w bazie danych? W jaki sposób powiązujemy konkretnego usera z konkretnym miejscem? Sytuacja w, której chcemy dodać miejsca swojego znajomego, czy wtedy korzystamy z tego samego dokumentu (konkretne miejsce) z kolekcji `places` i dodajemy następny user_id do jakieś listy? Trzeba to przemyśleć.

**Comment by debian-sh** [comment]
Będziemy raczej musieli powielać, bo co w sytuacji kiedy dany user będzie chcial edytować dane miejsce, a ktoś inny dodał je do swoich.

**Comment by Porkite** [comment]
Odpowiedziałeś sobie sam na pytanie, trzeba powielać, użytkownik nie koniecznie może będzie chciał zmieniać nazwę, ale już na pewno przypisze sobie miejsce do swoich kategorii.

**Comment by debian-sh** [comment]
Ok jeszcze musimy wiedzieć jak rozwiązać strukturę przetrzymywania zdjęć.

**Comment by debian-sh** [comment]
Kwestia kategorii pozostaje drugorzędna, jeśli chodzi o zdjęcia w samym frameworku Sealious nie mamy wyspecyfikowanego uploadu dla plików. Moduł dla tej funkcjonalności zostanie później zaimplementowany. Na razie zamykam to issue.
