### ISSUE TITLE
Nowy field-type dla category

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#53]
Rozwiązać to trzeba podobnie jak https://github.com/sowa-inc/SOWa/search?utf8=%E2%9C%93&q=pesel

Czyli tworzymy tablicę możliwych kategorii, tworzymy nowy field_type, podpiąć pod main.js.

Podpinanie tego pod UI to oddzielna kwestia.

**Comment by modliszka** [comment]
Czyli mam zrobić field-type w Sealiousie? Czy jakiś obiekt na podstawie czegoś, ale tylko w apce?

**Comment by debian-sh** [comment]
Robimy field-type dla Placetaga. Tak samo jak w SOWie Kuba zrobił field-type pesel.

**Comment by modliszka** [comment]
Wklejam tu pomocne rzeczy do projektowania grup kategorii i jak to ma wyglądać mniej więcej w praktyce:
http://www.poipoint.pl/pobierz_punkt_poi.php
http://www.poipoint.pl/point.php?poi_id=211283
