### ISSUE TITLE
Autouzpełnianie pól z OpenStreetMap

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#56]
User w trakcie dodawnia miejsca powinien mieć część danych już wypełnionych na przykład miasto albo w miarę możliwości miasto+ulica.

**Comment by modliszka** [comment]
Ok, więc powyższe już działa. Jednak trzeba to jeszcze zmodyfikować, bo po przesunięciu markera podpowiedź powinna być aktualizowana (?).
Czy jednak nie, zważywszy na to, że użytkownik może wpisać jakiś swój tekst, a przesunięcie markera by go usuwało... -> Do rozstrzygnięcia.

**Comment by debian-sh** [comment]
Ok spojrzę na to jutro, btw kategorie prawie gotowe

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
Zrobiłem, działa idealnie :)
