### ISSUE TITLE
UI - ikony kategorii

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#59]
Przygotować ikony dla kategorii

Lista kategorii w tym jsonie
https://github.com/debian-sh/Placetag/blob/7fa1991b66f2599908d86967efcd99db759c1c4c/placetag-app/poligon/category_subcategory_list.json

**Comment by Porkite** [comment]
w branchu issue#59 wrzucone są ikonki, do konsultacji kolory.

**Comment by debian-sh** [comment]
ok, kilka uwag:
- ikona sportu jest niewycentrowana,
- ikona motoryzacji ma za dużo szczegółów, proponuje jakiś prosty, front autka
- ikona turystyki lepsza byłaby coś w stylu mapa + kompas

**Comment by Porkite** [comment]
1. Zaraz poprawię ikonkę sportu,
2. Opona jest spoko i nie ma za dużo szczegółów, bo kiedy pomniejszysz ją do 32x32 to nadal widzisz, że to opona.
3. Przygotowałem też mapkę, ale po pomniejszeniu nie widać, że to mapka, mogę zrobić jeszcze kompas.

**Comment by debian-sh** [comment]
A nie lepiej do motoryzacji dać takie coś?
![Alt text](http://www.clipartbest.com/cliparts/ncE/LnB/ncELnBecA.png)

**Comment by Porkite** [comment]
mi koło bardziej się podoba, ale to obojętnie, mogę dać autko.

**Comment by debian-sh** [comment]
Pokazywałem ikony dwóm inny osobom i patrząc na koło nie wiedziały że to
koło.



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl
Sent from Xubuntu 14.04

2015-06-06 16:40 GMT+02:00 Piotr Grobelny <notifications@github.com>:

**Comment by debian-sh** [comment]
Zapomniałeś o kategorii "Urzędy i instytucje"

**Comment by Porkite** [comment]
Nie zapomniałem, ona jest zbyt ogólna, żeby jakąś sensowną ikonkę zapodać.

**Comment by Porkite** [comment]
Może nazwać ją inaczej i nawiązać z miejscami pracy.

**Comment by debian-sh** [comment]
Przedyskutuj z Moniką ;)



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl
Sent from Xubuntu 14.04

2015-06-06 21:49 GMT+02:00 Piotr Grobelny <notifications@github.com>:

**Comment by debian-sh** [comment]
Do poprawienia ikona kategorii "Zdrowie i uroda"

**Comment by Porkite** [comment]
już od rana siedzi w repo poprawione

**Comment by debian-sh** [comment]
w dev-model, czy znowu gdzie indziej? :)




*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl

**Comment by Porkite** [comment]
panie, dev model jak pan prosił

**Comment by debian-sh** [comment]
ok! :)



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl

**Comment by debian-sh** [comment]
Na razie jest ok, zamykam. Możesz pomyśleć o ikonę serca (kolorystyka no i może to serce z stetoskopem czy coś takiego).
