### ISSUE TITLE
Nowy feature: geolokalizacja wywoływana na żądanie

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#68]
User powinien mieć możliwość zgeolokalizowania swojej pozycji na mapie, po przez kliknięcie w jakiś button.

**Comment by modliszka** [comment]
Dodałam opcję geolokalizacji: https://github.com/debian-sh/Placetag/commit/27cae3306e8768ae764f1748157f7cc177dba606

**Comment by debian-sh** [comment]
Ok przerzucę ją prawdopodobnie w oddzielny komponent z przekazanymi propsami z komponentu mapy i powinno działać ładnie :)

**Comment by debian-sh** [comment]
Gotowe w https://github.com/debian-sh/Placetag/pull/75 niech ktoś przejrzy i zmerguje ;) Jak coś to piszcie komentarze.
