### ISSUE TITLE
Nowy feature: wybór kategorii i subkategorii w drop-down list

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#70]
Zmiany powinny znaleźć się w komponentach dla dodawania oraz edycji miejsca. Zwrócić uwagę na UI

**Comment by madjer22** [comment]
Ok kombinuje!

**Comment by debian-sh** [comment]
Spoko :)

**Comment by madjer22** [comment]
Gotowe w https://github.com/debian-sh/Placetag/commit/62a9d83517b6a5f877ef94235dc3191ca204608d

**Comment by debian-sh** [comment]
Ok zamykam
