### ISSUE TITLE
Leaflet to React

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#73]
Przepisanie wszystkich funkcjonalności w komponenty Reactowe. Branch https://github.com/debian-sh/Placetag/tree/_react

**Comment by debian-sh** [comment]
Aktualne problemy:

- [ ] `start.jsx	`		wielokrotne odczytywanie emitu o pozycji markera :<<
- [ ] `place-add.jsx`		przekazywanie po propsach tego co idzie z emitu new_marker_position
- [ ] `place-add.jsx`		problem z sweetalertem przy dodaniu miejsca (nie znika)
- [ ] `cała-aplikacja`	odświeżanie markerów i danych w całej aplikacji, wczytywanie zmian na rest api i zastosowywanie ich na widoku, places-view działa bo ma własnego GETa
- [ ] `place-find.jsx`	do naprawienia- napisanie od nowa, setView() etc.
- [ ] `sweetalert` 					wyabstrachowanie do oddzielnej klasy w postaci różnych funkcji?
- [ ] `animacje navigationboxa`		wyabstrachowanie do oddzielenj klasy w postaci różnych (umieszczenie wywołań w stosowanych miejscach w komponentach?)
- [ ] `marker-new.jsx`				emit value na dragend ale i też na add na mapie
- [ ] `places-view.jsx`				podpięcie wywołań z model.js
- [ ] `places-category.jsx` 			podpięcie wywołan z model.js

**Comment by madjer22** [comment]
PlaceFind zrobiony! Zmiany na branchu _react

**Comment by debian-sh** [comment]
- [ ] `ui`		module dla animacji
- [ ] `place-add.jsx	`		lista kategorii

**Comment by madjer22** [comment]
Przepisałem selecty w komponent Reactowy, żeby nie dublować kodu. ;)

**Comment by debian-sh** [comment]
Za chwilę sprawdzę :+1:

**Comment by debian-sh** [comment]
Mega fajnie rozwiązane
