### ISSUE TITLE
Poprawienie wyszukiwania miejsc

### ISSUE THREAD

**Issue by modliszka** [debian-sh/Placetag#76]
Podczas wyszukiwania następujących miejsc pojawia się puste pole (jest miejsce, ale nie są wyświetlone żadne dane z nim związane):
- Ojcowski Park Narodowy
- rudawski
- stawy milickie (jest tylko gmina)
- zamek czocha (numer + powiat)
- kwidzyn zamek (ulica, miejscowość)

**Comment by debian-sh** [comment]
Egzotyczne miejsca :)

**Comment by debian-sh** [comment]
Może w zróbmy tak że jeśli miejsce nie zawiera informacji, które możemy wyświetlić to wyświetlajmy nazwę, którą wpisał user? Chyba że masz lepszy pomysł :)

**Comment by debian-sh** [comment]
Co w temacie?

**Comment by modliszka** [comment]
Naprawione na branchu issue#76_fix_searching_places.
