### ISSUE TITLE
UI: Odświeżenie interfejsów

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#77]
Należy opracować spójny wygląd interfejsu dla nav-left-box'a i głównej aktywności ekranu na Androidzie

**Comment by debian-sh** [comment]
Możesz zrobić spójne mockupy dla obu klientów. Mój pomysł jest taki żeby w dużej mierze interfejsy nav-left-boxa pokrywały się z klientem androidowym

**Comment by Porkite** [comment]
jak dostanę sygnał od Macieja, że zaczyna działać z androidem, spotkam się z nim i opracujemy to wspólnie.

**Comment by debian-sh** [comment]
Ok miej tylko na uwadze że za dużo nie trzeba zmieniać w kliencie webowym

**Comment by debian-sh** [comment]
Co w temacie?

**Comment by Porkite** [comment]
Pisz do Macieja na czacie, tutaj może nie odczytać.

**Comment by debian-sh** [comment]
Temat zamknięty do sierpnia.
