### ISSUE TITLE
UI: Kolorystyka

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#78]
Co sądzicie żeby pójść w odcienie ciemnego fioletu, zamiast aktualnego koloru?

**Comment by Porkite** [comment]
Podoba mi się aktualną kolorystyka. O jakim odcieniu mówisz dokładnie?

**Comment by debian-sh** [comment]
![image](https://cloud.githubusercontent.com/assets/5663277/8410597/8b4dc1ea-1e7f-11e5-9c50-ec53900cb1ba.png)

Myślałem o czymś takim :)

**Comment by debian-sh** [comment]
![image](https://cloud.githubusercontent.com/assets/5663277/8410756/917e24aa-1e80-11e5-8009-a82ccedb0e22.png)
Moja druga propozycja

**Comment by Porkite** [comment]
druga propozycja całkiem ładna

**Comment by debian-sh** [comment]
Mi też się bardzo podoba co na to reszta?

**Comment by debian-sh** [comment]
Druga propozycja znajdzie się na devie. :) Jest bardziej wyrazista

**Comment by Porkite** [comment]
![image](https://cloud.githubusercontent.com/assets/4449083/8498338/c7879754-2185-11e5-80da-4e41ac789506.png)
Kategorie trochę źle się układają, trzeba też pozmieniać wszystkie elementy które mają w sobie jeszcze stary kolor: ikonki, ekran logowania. Przydałaby się też odpowiedź od reszty, bo mi oba kolory pasują. (w przyszłości można dać użytkownikowi wybór koloru layoutu)

**Comment by debian-sh** [comment]
Masz zcacheowanego starego cssa, wejdź sobie przez incognito. Bardzo ładnie stare kolory komponują się z nowym kolorem buttonów.

**Comment by debian-sh** [comment]
Naprawione, przetestuj :)
