### ISSUE TITLE
Pełno ekranowe wyświetlanie zdjęcia

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#82]
Wyświetlanie powiększonego zdjęcia po kliknięciu w nie.

**Comment by debian-sh** [comment]
Potrzebna ikona "powiększ"

**Comment by Porkite** [comment]
Jak przyjdę z pracy to zrobię

**Comment by debian-sh** [comment]
ok

**Comment by debian-sh** [comment]
Podrzucisz ikonkę jeszcze raz na branch'a https://github.com/debian-sh/Placetag/tree/issue%2382_fullscreen_photo?

**Comment by debian-sh** [comment]
zawieszam.
