### ISSUE TITLE
Zmiany w wyświetlaniu kategorii

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#89]
- Trzeba zmienić wygląd kategorii na kółka co będzie bardziej spójne z aktualnym interfejsem
- Zmodyfikować komponent / napisać nowy, aby dana kategoria była kolorowa kiedy jakieś miejsca się w niej znajdują bądź licznik miejsc przy grafice kategorii

**Comment by Porkite** [comment]
"Zmodyfikować komponent / napisać nowy, aby dana kategoria była kolorowa kiedy jakieś miejsca się w niej znajdują bądź licznik miejsc przy grafice kategorii"
Bardzo spoko pomysł.
Pozdrawiam

**Comment by debian-sh** [comment]
Chcesz zająć się punktem 1?

**Comment by Porkite** [comment]
spoko, tylko w weekend, bo w tygodniu nie mam kiedy za bardzo

**Comment by debian-sh** [comment]
Punkt 1, rozwiązany w https://github.com/debian-sh/Placetag/pull/93
