### ISSUE TITLE
Nowy feature: wyświetlanie popupów po najechaniu na button

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#92]

**Comment by Porkite** [comment]
Co w popupie? Miniaturka zdjęcia też?

**Comment by debian-sh** [comment]
Ale w jakim celu miniaturka zdjęcia? Chodzi o to że po najechaniu na button, np. lupy user nie wie co się stanie po kliknięciu. Dlatego trzeba wyświetlić dla niego stosowny dymek. W tym przykładzie "Wyszukaj miejsce"

**Comment by Porkite** [comment]
Pewnie, mój błąd, pomyślałem o popupie po najechaniu na miejsce na mapie.

**Comment by debian-sh** [comment]
Częściowo rozwiązane: https://github.com/debian-sh/Placetag/tree/issues%2392_popups_button

**Comment by debian-sh** [comment]
Rozwiązane: https://github.com/debian-sh/Placetag/pull/93
