### ISSUE TITLE
Mockup dla strony z parallax oraz login boxy

### ISSUE THREAD

**Issue by debian-sh** [debian-sh/Placetag#95]
Przydatne linki:
http://codepen.io/keithclark/pen/JycFw
http://keithclark.co.uk/articles/pure-css-parallax-websites/demo3-webkit-overflow-fix/

**Comment by Porkite** [comment]
jak to widzisz? na początku logowanie, niżej info? Czy raczej na stronie startowej będzie w rogu ikonka do logowania.

**Comment by debian-sh** [comment]
Np. 95vh ekranu z logowaniem i później klika opisów funkcjonalności na kolejnych ekranach, a w tle ładne screeny z openstreetmap. :)

**Comment by Porkite** [comment]
ja tu jeszcze widzę ładne ikonki. NP wpis o tym, że można mobilnie i desktopowo działać + ikonka lapka i komóreczki, gdzieś jakiś kompas. Mam pomysł jak to wizualnie może wyglądać, żeby było skromnie i nie oczojebnie.

**Comment by debian-sh** [comment]
Ok w takim razie zrób graficzny mockup jakby to miało gotowo wyglądać :)

**Comment by Porkite** [comment]
Z chęcią, ale teraz za bardzo nie mam dostępu do mojego laptopa. Myślę, że ogarnę to w środku tygodnia jakoś. Nie chcę robić na kartce tego ;)

**Comment by debian-sh** [comment]
Ok, gotowa grafika zrobiona w jakimś ux deaignerze albo Photoshopie :) Żeby później szybko na tym zbudować szablon.

**Comment by Porkite** [comment]
illustrator ;)

**Comment by debian-sh** [comment]
Yep jestem tylko programista :)

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Porkite** [comment]
![test](https://cloud.githubusercontent.com/assets/4449083/9476225/d48bf76e-4b6b-11e5-9abd-f867babe87e7.png)
Kliknij, żeby obejrzeć w rozmiarze 1:1 i uniknąć aliasingu.

**Comment by Porkite** [comment]
tło się przesuwa w innym tempie, a dymki pojawiają się/wskakują na ekran (do przemyślenia)

**Comment by debian-sh** [comment]
Fajne dymki, ale wolałbym klasyczne boxy z contentem rozciągnięte na 100%

**Comment by Porkite** [comment]
zapodaj jakiś przykład i może coś wymyślimy razem

**Comment by debian-sh** [comment]
Może coś takiego jak na Spotify :)

**Comment by Porkite** [comment]
ładnie, ale bez wodotrysków ;)

**Comment by debian-sh** [comment]
Prostota wysoce wskazana :)

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
I jak wymyśliłeś jakiś mockup pokroju Spotify? :>

**Comment by Porkite** [comment]
nie, razem to musimy zrobić

**Comment by debian-sh** [comment]
Przygotuj swoją propozycję

**Comment by Porkite** [comment]
Koncepcyjny png jak wyżej z uwględnieniem login boxa?
Mogę trochę zmienić to co pokazałem wyżej, aby było bardziej spotifaju podobne.

**Comment by debian-sh** [comment]
tak.

**Comment by debian-sh** [comment]
up^

**Comment by debian-sh** [comment]
Podobnie mogłaby wyglądać nasza strona startowa http://www.invisionapp.com/

**Comment by debian-sh** [comment]
Zawieszam.
